// src/lib/submissions.js
// Firestore "submissions" collection access layer.
//
// Schema:
// {
//   assignmentId,       string
//   studentId,          string
//   submittedAt,        Timestamp
//   submissionType,     "file" | "text"
//   submissionFileUrl,  string | null  — null for private Supabase files
//   submissionFilePath, string | null  — Supabase Storage path (submissions bucket)
//   filename,           string | null  — UUID filename generated by storage service
//   originalFileName,   string | null  — original file.name from the browser
//   fileSize,           number | null  — bytes
//   mimeType,           string | null  — MIME type
//   textSubmission,     string | null
//   lateSubmission,     boolean
//   status,             "on_time" | "late"
// }

import {
  collection,
  doc,
  addDoc,
  getDoc,
  getDocs,
  updateDoc,
  deleteDoc,
  onSnapshot,
  query,
  where,
  orderBy,
  limit,
  Timestamp,
} from "firebase/firestore";
import { db } from "./firebase";

const COLLECTION = "submissions";

function mapDoc(snap) {
  if (!snap.exists()) return null;
  return { id: snap.id, ...snap.data() };
}

function toTimestamp(value) {
  if (value instanceof Timestamp) return value;
  if (value instanceof Date) return Timestamp.fromDate(value);
  throw new Error("[submissions] deadline must be a Date or Firestore Timestamp.");
}

/**
 * Ownership lookup: the one submission (if any) a given student has
 * made for a given assignment.
 *
 * @param {string} assignmentId
 * @param {string} studentId
 * @returns {Promise<object|null>}
 */
export async function getSubmissionForAssignment(assignmentId, studentId) {
  if (!assignmentId || !studentId) {
    throw new Error(
      "[submissions] getSubmissionForAssignment requires assignmentId and studentId."
    );
  }
  try {
    const q = query(
      collection(db, COLLECTION),
      where("assignmentId", "==", assignmentId),
      where("studentId", "==", studentId),
      limit(1)
    );
    const snapshot = await getDocs(q);
    return snapshot.empty ? null : mapDoc(snapshot.docs[0]);
  } catch (err) {
    console.error("[submissions] getSubmissionForAssignment failed:", err);
    throw err;
  }
}

/**
 * Create a submission.
 *
 * Accepts either a file submission (submissionFilePath for private Supabase
 * files) or a text submission (textSubmission). Exactly one must be provided.
 * Enforces one submission per (assignmentId, studentId) pair.
 *
 * @param {{
 *   assignmentId:       string,
 *   studentId:          string,
 *   submissionFileUrl?: string|null,
 *   submissionFilePath?: string|null,
 *   filename?:          string|null,
 *   originalFileName?:  string|null,
 *   fileSize?:          number|null,
 *   mimeType?:          string|null,
 *   textSubmission?:    string|null,
 *   deadline:           import("firebase/firestore").Timestamp | Date,
 * }} params
 * @returns {Promise<{ id: string; status: "on_time"|"late" }>}
 */
export async function createSubmission({
  assignmentId,
  studentId,
  submissionFileUrl = null,
  submissionFilePath = null,
  filename = null,
  originalFileName = null,
  fileSize = null,
  mimeType = null,
  textSubmission = null,
  deadline,
}) {
  if (!assignmentId) throw new Error("[submissions] assignmentId is required.");
  if (!studentId) throw new Error("[submissions] studentId is required.");
  if (!submissionFilePath && !textSubmission) {
    throw new Error("[submissions] Provide either submissionFilePath or textSubmission.");
  }

  const existing = await getSubmissionForAssignment(assignmentId, studentId);
  if (existing) {
    throw new Error("[submissions] A submission already exists for this assignment.");
  }

  const submittedAt = Timestamp.now();
  const lateSubmission =
    deadline != null
      ? submittedAt.toMillis() > toTimestamp(deadline).toMillis()
      : false;
  const status = lateSubmission ? "late" : "on_time";
  const submissionType = submissionFilePath ? "file" : "text";

  const payload = {
    assignmentId,
    studentId,
    submittedAt,
    submissionType,
    // submissionFileUrl is null for private bucket files — use submissionFilePath
    // to generate a signed URL on demand
    submissionFileUrl,
    submissionFilePath,
    filename,
    originalFileName,
    fileSize,
    mimeType,
    textSubmission,
    lateSubmission,
    status,
  };

  try {
    const ref = await addDoc(collection(db, COLLECTION), payload);
    return { id: ref.id, status };
  } catch (err) {
    console.error("[submissions] createSubmission failed:", err);
    throw err;
  }
}

/**
 * Fetch a single submission by its doc id. Returns null if not found.
 * @param {string} id
 */
export async function getSubmission(id) {
  if (!id) throw new Error("[submissions] getSubmission requires an id.");
  try {
    const snap = await getDoc(doc(db, COLLECTION, id));
    return mapDoc(snap);
  } catch (err) {
    console.error("[submissions] getSubmission failed:", err);
    throw err;
  }
}

/**
 * All submissions made by a student, newest first.
 * @param {string} studentId
 */
export async function getSubmissionsForStudent(studentId) {
  if (!studentId) {
    throw new Error("[submissions] getSubmissionsForStudent requires a studentId.");
  }
  try {
    const q = query(
      collection(db, COLLECTION),
      where("studentId", "==", studentId),
      orderBy("submittedAt", "desc")
    );
    const snapshot = await getDocs(q);
    return snapshot.docs.map(mapDoc);
  } catch (err) {
    console.error("[submissions] getSubmissionsForStudent failed:", err);
    throw err;
  }
}

/**
 * All submissions for a given assignment, oldest first — admin tracker.
 * @param {string} assignmentId
 */
export async function getSubmissionsForAssignment(assignmentId) {
  if (!assignmentId) {
    throw new Error("[submissions] getSubmissionsForAssignment requires an assignmentId.");
  }
  try {
    const q = query(
      collection(db, COLLECTION),
      where("assignmentId", "==", assignmentId),
      orderBy("submittedAt", "asc")
    );
    const snapshot = await getDocs(q);
    return snapshot.docs.map(mapDoc);
  } catch (err) {
    console.error("[submissions] getSubmissionsForAssignment failed:", err);
    throw err;
  }
}

/**
 * Live subscription scoped to exactly one of { assignmentId } or
 * { studentId } — never the whole collection.
 *
 * @param {{ assignmentId?: string; studentId?: string }} filter
 * @param {(items: object[]) => void} onChange
 * @param {(err: Error) => void} [onError]
 * @returns {() => void} unsubscribe
 */
export function subscribeToSubmissions({ assignmentId, studentId } = {}, onChange, onError) {
  if (!assignmentId && !studentId) {
    throw new Error("[submissions] subscribeToSubmissions requires assignmentId or studentId.");
  }
  if (assignmentId && studentId) {
    throw new Error("[submissions] subscribeToSubmissions accepts only one filter at a time.");
  }

  const q = assignmentId
    ? query(
        collection(db, COLLECTION),
        where("assignmentId", "==", assignmentId),
        orderBy("submittedAt", "asc")
      )
    : query(
        collection(db, COLLECTION),
        where("studentId", "==", studentId),
        orderBy("submittedAt", "desc")
      );

  return onSnapshot(
    q,
    (snapshot) => onChange(snapshot.docs.map(mapDoc)),
    (err) => {
      console.error("[submissions] subscribeToSubmissions error:", err);
      onError?.(err);
    }
  );
}

/**
 * Partial update. Submissions are otherwise immutable by design —
 * this exists for admin-side corrections only.
 * @param {string} id
 * @param {object} updates
 */
export async function updateSubmission(id, updates) {
  if (!id) throw new Error("[submissions] updateSubmission requires an id.");
  try {
    await updateDoc(doc(db, COLLECTION, id), updates);
  } catch (err) {
    console.error("[submissions] updateSubmission failed:", err);
    throw err;
  }
}

/**
 * Permanently delete a submission.
 * @param {string} id
 */
export async function deleteSubmission(id) {
  if (!id) throw new Error("[submissions] deleteSubmission requires an id.");
  try {
    await deleteDoc(doc(db, COLLECTION, id));
  } catch (err) {
    console.error("[submissions] deleteSubmission failed:", err);
    throw err;
  }
}
